service: hello-python-api-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

custom:
  serverless-offline:
    lambdaPort: 4002
    httpPort: 4000

plugins:
    - serverless-offline

functions:
  hello:
    handler: handler.hello
    timeout: 300
    memorySize: 128
    events:
        - http:
              path: hello-world
              method: get
              cors: true