service: api-timeout-test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  memorySize: 128
  timeout: 30

package:
  individually: true
  patterns:
    - "!*/**"

functions:
  api-timeout-test-trigger:
    name: api-timeout-test-trigger
    handler: api.handler
    package:
      patterns:
        - "api.js"
    events:
      - http:
          method: GET
          path: /

  api-timeout-test-fn:
    name: api-timeout-test-fn
    handler: lambda.handler
    package:
      patterns:
        - "lambda.js"
