# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: lambda

frameworkVersion: "3"

custom:
  profiles:
    serverless: deploy
  var: testing

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  region: sa-east-1
  profile: ${self:custom.profiles.serverless}
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  environment:
    myvar: ${self:custom.var}

package:
  individually: true
  patterns:
    - "!node_modules/**"

plugins:
  - serverless-offline

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    name: hello-world-basic-api-${opt:stage}
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    timeout: 300
    memorySize: 128
    events:
      - http:
          path: hello-world
          method: get
          cors: true

  helloWorld2:
    name: hello-world-2-basic-api-${opt:stage}
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    timeout: 300
    memorySize: 128
    events:
      - http:
          path: hello-world-2
          method: get
          cors: true
