service: hello-node-event-lambda

frameworkVersion: "2"

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  versionFunctions: false

functions:
  hello:
    name: hello-node-event-lambda
    handler: handler.run
    events:
      - schedule:
          rate: cron(0 0 ? * * *)
